apiVersion: v1
name: vsphere-cpi-csi
version: 2.1.0
appVersion: 2.1.0
description: vSphere CPI manager and CSI drivers
keywords:
  - vsphere
  - vmware
  - esxi
  - cpi
  - csi
  - storage
icon: file://../vsphere_7.png
maintainers:
  - name: Stefan van Gastel
    email: stefanvangastel@gmail.com
  - name: Tom Houweling
    email: thouweling@gmail.com
engine: gotpl
