images:
  vsphereCloudControllerManager: "gcr.io/cloud-provider-vsphere/cpi/release/manager:v1.1.0"
  csiAttacher: "quay.io/k8scsi/csi-attacher:v2.0.0"
  csiDriver: "gcr.io/cloud-provider-vsphere/csi/release/driver:v2.0.0"
  livenessProbe: "quay.io/k8scsi/livenessprobe:v1.1.0"
  vsphereSyncer: "gcr.io/cloud-provider-vsphere/csi/release/syncer:v2.0.0"
  csiProvisioner: "quay.io/k8scsi/csi-provisioner:v1.4.0"
  csiResizer: "quay.io/k8scsi/csi-resizer:v0.3.0"
  nodeDriverRegistrar: "quay.io/k8scsi/csi-node-driver-registrar:v1.2.0"

vcenter:
  # host: vcenter.example.com
  insecurehost: true
  # username: admin 
  # password: root
  # datacenter: DC1

storageclass:
  name: vsphere-csi
  default: true
  fstype: ext4
  # storagepolicyname: my-storage-policy
  # datastoreurl: ds:///vmfs/volumes/vsan:528c27f173c2088e-2126e911985dc3aa/